language: python

python: "3.9"

install:
  - pip install -r requirements.txt

script:
  - coverage run manage.py test

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: thaimoung

after_success:
  - bash <(curl -s https://codecov.io/bash)