# Generated by Django 3.2.8 on 2021-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_text',
            new_name='topic_name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('', '----------'), ('news', 'News'), ('sports', 'Sports'), ('game', 'Games'), ('fashion', 'Fashion'), ('technology', 'Technology')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(default='', max_length=20),
        ),
    ]
