# Generated by Django 3.2.8 on 2021-11-28 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_auto_20211128_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
