# Generated by Django 3.2.8 on 2021-11-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_post_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
