# Generated by Django 3.2.8 on 2021-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20211119_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('', '----------'), ('news', 'News'), ('sports', 'Sports'), ('games', 'Games'), ('fashion', 'Fashion'), ('technology', 'Technology')], default='', max_length=20),
        ),
    ]
