# Generated by Django 3.2.8 on 2021-11-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_alter_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
