# Generated by Django 3.2.8 on 2021-11-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('', '----------'), ('news', 'News'), ('harassment', 'Harassment'), ('sports', 'Sports'), ('games', 'Games'), ('fashion', 'Fashion'), ('technology', 'Technology'), ('music', 'Music'), ('gourmet', 'Gourmet')], default='', max_length=20),
        ),
    ]
